# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.FileField(blank=True, null=True, upload_to='submits/')),
                ('verdict', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
