# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_acc_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
