# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problem_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test',
            field=models.FileField(upload_to='tests/'),
        ),
    ]
