# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20160608_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='test',
            new_name='test_in',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_out',
            field=models.FileField(default='', upload_to='tests/'),
            preserve_default=False,
        ),
    ]
